version: '3.4'

services:
  database_pg:
    image: postgres
    container_name: databasePG
    restart: always
    ports:
      - 5432:5432
    environment:
      TZ: utc
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: test
      POSTGRES_DB: pji240
    volumes:
      - pgdata:/data/postgres
  app_pji240:
    build: .
    container_name: AppPJI240
    volumes:
      - .:/usr/app
    environment:
      TZ: utc
      NODE_ENV: production
    ports:
      - 3333:3333
    links:
      - database_pg
    depends_on:
      - database_pg
volumes:
  pgdata:
    driver: local
